{
 "title": "Kubernetes http",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(apache_up,namespace)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(apache_up{namespace=\"$namespace\"},app_kubernetes_io_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Data Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(rate(apache_sent_kilobytes_total{namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(apache_up{namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request handled (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(apache_accesses_total{namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"}[5m]))",
     "legendFormat": "Requests handled"
    }
   ]
  },
  {
   "title": "Scoreboard Detail",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(apache_scoreboard{state=\"closing\", namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"})",
     "legendFormat": "Threads: closing"
    },
    {
     "expr": "sum(apache_scoreboard{state=\"keepalive\", namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"})",
     "legendFormat": "Threads: keepalive"
    },
    {
     "expr": "sum(apache_scoreboard{state=\"writing\", namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"})",
     "legendFormat": "Threads: writing"
    },
    {
     "expr": "sum(apache_scoreboard{state=\"closing\", namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"})",
     "legendFormat": "Threads: closing"
    },
    {
     "expr": "sum(apache_scoreboard{state=\"idle\", namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"})",
     "legendFormat": "Threads: idle"
    },
    {
     "expr": "sum(apache_scoreboard{state=\"logging\", namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"})",
     "legendFormat": "Threads: logging"
    },
    {
     "expr": "sum(apache_scoreboard{state=\"read\", namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"})",
     "legendFormat": "Threads: reading"
    },
    {
     "expr": "sum(apache_scoreboard{state=\"reply\", namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"})",
     "legendFormat": "Threads: replying"
    }
   ]
  },
  {
   "title": "Workers State (General)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(apache_workers{state=\"busy\", namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"})",
     "legendFormat": "Workers: busy"
    },
    {
     "expr": "sum(apache_workers{state=\"idle\", namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"})",
     "legendFormat": "Workers: idle"
    }
   ]
  },
  {
   "title": "Workers State (General)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(apache_workers{state=\"busy\", namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"})",
     "legendFormat": "Workers: busy"
    },
    {
     "expr": "sum(apache_workers{state=\"idle\", namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"})",
     "legendFormat": "Workers: idle"
    }
   ]
  },
  {
   "title": "Connections States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(apache_connections{state=\"closing\", namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"})",
     "legendFormat": "Connections: closing"
    },
    {
     "expr": "sum(apache_connections{state=\"keepalive\", namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"})",
     "legendFormat": "Connections: keepalive"
    },
    {
     "expr": "sum(apache_connections{state=\"writing\", namespace=\"${namespace}\", app_kubernetes_io_name=\"${app}\"})",
     "legendFormat": "Connections: writing"
    }
   ]
  }
 ]
}