apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "labels" . | indent 4 | trim }}
data:
  noop: "noop"
{{- range $k, $v := .Values.configenvs }}
{{ $k | indent 2}}: {{ $v | quote}}
{{- end }}
