{{- $root = . -}}
{{- $service := .Values.service | default dict -}}
{{- if eq $service.enable "true" }}
{{- if gt (len $service.httproutes) 0 -}}
{{- $hr := $service.httproutes -}}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "name" $root | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  parentRefs:
  - name: {{ $hr.gatewayName | default "gateway" }}
    namespace: {{ $hr.gatewayNameSpace | default "istio-system" }}
  {{- if $hr.hostnames }}
  hostnames:
    - {{- printf "%s.%s" (include "name" $root) .Release.Namespace }}
  rules:
  - matches:
    - path: 
        type: PathPrefix
        value: /
    backendRefs:
      - name: {{ printf "%s-prv" (include "name" $root) | quote }}
        port: {{ $service.servicePort }}
        weight: 100
{{- end }}
{{- end }}
{{- end -}}