{
 "title": "Aggregato per Deployment Copy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase,namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_spec_replicas{namespace=\"${ns}\"},deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"${ns}\",pod=~\"^${deployment}-[a-z0-9]+-[a-z0-9]+$\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"${ns}\",pod=~\"^${deployment}-[a-z0-9]+-[a-z0-9]+$\"}[5m])) by (pod)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "-1*sum(rate(container_network_transmit_bytes_total{namespace=\"${ns}\",pod=~\"^${deployment}-[a-z0-9]+-[a-z0-9]+$\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"${ns}\",pod=~\"^${deployment}-[a-z0-9]+-[a-z0-9]+$\"}[5m])) by (pod)",
     "legendFormat": "Writes {{pod}}"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"${ns}\",pod=~\"^${deployment}-[a-z0-9]+-[a-z0-9]+$\"}[5m])) by (pod)",
     "legendFormat": "Reads {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Resources",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${ns}\",pod=~\"^${deployment}-[a-z0-9]+-[a-z0-9]+$\"}[$__rate_interval]))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"${ns}\",pod=~\"^${deployment}-[a-z0-9]+-[a-z0-9]+$\",resource=\"cpu\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"${ns}\",pod=~\"^${deployment}-[a-z0-9]+-[a-z0-9]+$\",resource=\"cpu\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"${ns}\",pod=~\"^${deployment}-[a-z0-9]+-[a-z0-9]+$\"}[5m])) / ignoring(id) sum(increase(container_cpu_cfs_periods_total{}[5m]))",
     "legendFormat": "Throttling"
    }
   ]
  },
  {
   "title": "Memory Resources",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(max(container_memory_working_set_bytes{namespace=\"${ns}\",pod=~\"^${deployment}-[a-z0-9]+-[a-z0-9]+$\"} / (1024*1024)))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"${ns}\",pod=~\"^${deployment}-[a-z0-9]+-[a-z0-9]+$\",resource=\"memory\"}) / (1024*1024)",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"${ns}\",pod=~\"^${deployment}-[a-z0-9]+-[a-z0-9]+$\",resource=\"memory\"}/ (1024*1024))",
     "legendFormat": "Limit"
    }
   ]
  }
 ]
}