{
 "title": "Elasticsearch v2",
 "tags": [
  "infra",
  "b2c",
  "elastic"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_status,app_kubernetes_io_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{color=\"green\",app_kubernetes_io_instance=~\"$cluster\"} * 1 + ignoring(color) elasticsearch_cluster_health_status{color=\"yellow\",app_kubernetes_io_instance=~\"$cluster\"} * 2 + ignoring(color) elasticsearch_cluster_health_status{color=\"red\",app_kubernetes_io_instance=~\"$cluster\"} * 3)"
    }
   ]
  },
  {
   "title": "Running Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_nodes{app_kubernetes_io_instance=~\"$cluster\"})/count(elasticsearch_cluster_health_number_of_nodes{app_kubernetes_io_instance=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active Data Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{app_kubernetes_io_instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{app_kubernetes_io_instance=~\"$cluster\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{app_kubernetes_io_instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Active Primary Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{app_kubernetes_io_instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{app_kubernetes_io_instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{app_kubernetes_io_instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{app_kubernetes_io_instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Delayed Unassigned Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{app_kubernetes_io_instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Documents indexed (primary)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs_primary{app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "Documenti (primari)"
    }
   ]
  },
  {
   "title": "Index Size (primary + replica)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_store_size_bytes{app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "Index Size"
    }
   ]
  },
  {
   "title": "Documents Indexed Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{app_kubernetes_io_instance=~\"$cluster\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_total{app_kubernetes_io_instance=~\"$cluster\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_queue_count{app_kubernetes_io_instance=~\"$cluster\", type!=\"management\"}) by (type)",
     "legendFormat": "Type: {{type}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_os_mem_used_bytes{app_kubernetes_io_instance=~\"$cluster\"} + elasticsearch_os_mem_free_bytes{app_kubernetes_io_instance=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Memory Free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_os_mem_free_bytes{app_kubernetes_io_instance=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "JVM Heap Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_jvm_memory_max_bytes{area=\"heap\",app_kubernetes_io_instance=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Thread Pools",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_active_count{app_kubernetes_io_instance=~\"$cluster\", type!=\"management\"}) by (type)",
     "legendFormat": "Type: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread pool rejections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_thread_pool_rejected_count{app_kubernetes_io_instance=~\"$cluster\", type!=\"management\"}[5m])",
     "legendFormat": "{{ name }} {{ type }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "elasticsearch_os_cpu_percent{app_kubernetes_io_instance=~\"$cluster\"}",
     "legendFormat": "OS {{name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "failure_tstamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "elasticsearch_process_cpu_percent{app_kubernetes_io_instance=~\"$cluster\"}",
     "legendFormat": "ES {{name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "failure_tstamp"
    }
   ]
  },
  {
   "title": "Avg Heap in 15min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(elasticsearch_jvm_memory_used_bytes{area=\"heap\",app_kubernetes_io_instance=~\"$cluster\"}[15m]) / elasticsearch_jvm_memory_max_bytes{area=\"heap\",app_kubernetes_io_instance=~\"$cluster\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Search latency (avg, 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_time_seconds{app_kubernetes_io_instance=~\"$cluster\"}[5m]) / rate(elasticsearch_indices_search_query_total{app_kubernetes_io_instance=~\"$cluster\"}[5m])",
     "legendFormat": "query {{name}}"
    },
    {
     "expr": "rate(elasticsearch_indices_search_fetch_time_seconds{app_kubernetes_io_instance=~\"$cluster\"}[5m]) / rate(elasticsearch_indices_search_fetch_total{app_kubernetes_io_instance=~\"$cluster\"}[5m])",
     "legendFormat": "fetch {{name}}"
    }
   ]
  },
  {
   "title": "GC seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_sum{app_kubernetes_io_instance=~\"$cluster\"}[5m])",
     "legendFormat": "{{ name }} {{ gc }}"
    }
   ]
  },
  {
   "title": "Disk free %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * elasticsearch_filesystem_data_available_bytes{app_kubernetes_io_instance=~\"$cluster\"} / elasticsearch_filesystem_data_size_bytes{app_kubernetes_io_instance=~\"$cluster\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}