{
 "title": "Monitor Pod CPU and Memory usage",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase,namespace)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(kube_pod_owner{owner_kind=~\"DaemonSet|StatefulSet|ReplicaSet\",namespace=~\"[[ns]]\"},owner_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_owner{owner_name=~\"[[app]]\",namespace=~\"[[ns]]\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{pod=\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=\"$pod\"}[5m]))",
     "legendFormat": "Recv"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=\"$pod\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=\"$pod\"}[5m])) by (container_name,device)",
     "legendFormat": "{{device}} writes"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=\"$pod\"}[5m])) by (container_name,device)",
     "legendFormat": "{{device}} reads"
    }
   ]
  },
  {
   "title": "CPU(cores)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{pod=\"$pod\",container=\"$container\"}[5m])) by (container)",
     "legendFormat": "container usage"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=\"$pod\",container=\"$container\",resource=\"cpu\"}) by (container)",
     "legendFormat": "container request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=\"$pod\",container=\"$container\",resource=\"cpu\"}) by (container)",
     "legendFormat": "container limit"
    },
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{pod=\"$pod\",container=\"$container\"}[5m])) / ignoring(id) sum(increase(container_cpu_cfs_periods_total{}[5m]))",
     "legendFormat": "throttling "
    }
   ]
  },
  {
   "title": "Memory(Mi)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{container=\"$container\",pod=\"$pod\"} / (1024*1024)) by (container)",
     "legendFormat": "container usage"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{container=\"$container\",pod=\"$pod\",resource=\"memory\"}) by (container) / (1024*1024)",
     "legendFormat": "container request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=\"$pod\",container=\"$container\",resource=\"memory\"}) by (container) / (1024*1024)",
     "legendFormat": "container limit"
    }
   ]
  },
  {
   "title": "Expect CPU Setting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max by (container,owner_name)((rate(container_cpu_usage_seconds_total{pod=\"$pod\",container=\"$container\"}[5m])) * on(pod) group_left(owner_name) avg by (namespace,pod,owner_name)(kube_pod_owner{owner_kind=~\"DaemonSet|StatefulSet|ReplicaSet\"}))",
     "legendFormat": "Conservative Strategy "
    },
    {
     "expr": "quantile by (owner_name,container)(0.99,(rate(container_cpu_usage_seconds_total{pod=\"$pod\",container=\"$container\"}[5m])) * on(pod) group_left(owner_name) avg by (namespace,pod,owner_name)(kube_pod_owner{owner_kind=~\"DaemonSet|StatefulSet|ReplicaSet\"}))",
     "legendFormat": "Aggressive Strategy"
    }
   ]
  },
  {
   "title": "Expect Memory Setting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "max by (owner_name,container)((container_memory_usage_bytes{container=\"$container\",pod=\"$pod\"}) * on(pod) group_left(owner_name) avg by (namespace,pod,owner_name)(kube_pod_owner{owner_kind=~\"DaemonSet|StatefulSet|ReplicaSet\"})) / (1024*1024)",
     "legendFormat": "Conservative Strategy"
    },
    {
     "expr": "quantile by (owner_name,container)(0.99,(container_memory_usage_bytes{container=\"$container\",pod=\"$pod\"}) * on(pod) group_left(owner_name) avg by (namespace,pod,owner_name)(kube_pod_owner{owner_kind=~\"DaemonSet|StatefulSet|ReplicaSet\"})) / (1024*1024)",
     "legendFormat": "Aggressive Strategy"
    }
   ]
  }
 ]
}