{
 "title": "PHP-FPM",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(phpfpm_up,namespace)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(phpfpm_up{namespace=\"[[namespace]]\"},app_kubernetes_io_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Aggregate Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(phpfpm_process_request_duration{app_kubernetes_io_name=~\"[[app]]\",namespace=~\"[[namespace]]\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "min(phpfpm_process_request_duration{app_kubernetes_io_name=~\"[[app]]\",namespace=~\"[[namespace]]\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "max(phpfpm_process_request_duration{app_kubernetes_io_name=~\"[[app]]\",namespace=~\"[[namespace]]\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "# of pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(phpfpm_up{app_kubernetes_io_name=\"$app\",namespace=\"$namespace\"} > 0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queued Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(phpfpm_listen_queue{app_kubernetes_io_name=\"$app\",namespace=\"$namespace\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Scrape failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(phpfpm_scrape_failures{app_kubernetes_io_name=\"$app\",namespace=\"$namespace\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slow requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(phpfpm_slow_requests{app_kubernetes_io_name=\"$app\", namespace=\"$namespace\"})    ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Process Utilisation",
   "type": "gauge",
   "description": "Utilisation of processes based on active/inactive processes",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  (sum(phpfpm_active_processes{app_kubernetes_io_instance=~\"[[app]].*\",namespace=~\"[[namespace]]\"}) by (pod) *100) \n  / \n  (sum(phpfpm_total_processes{app_kubernetes_io_instance=~\"[[app]].*\",namespace=~\"[[namespace]]\"}) by (pod))\n)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Max Children reached",
   "type": "stat",
   "description": "How many times was the maximum amount of children reached?",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(phpfpm_max_children_reached{app_kubernetes_io_name=\"$app\",namespace=\"$namespace\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accepted connections (rpm)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(delta(phpfpm_accepted_connections{app_kubernetes_io_instance=~\"[[app]]\", namespace=~\"[[namespace]]\"} [10m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# of processes by state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(phpfpm_process_state{app_kubernetes_io_name=\"$app\", namespace=\"$namespace\", state!='Total'}) by (state)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Duration by process",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(phpfpm_process_request_duration{app_kubernetes_io_name=\"$app\",namespace=\"$namespace\"}) by (pod,child)",
     "legendFormat": "{{pod}} {{child}}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Queued requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(phpfpm_listen_queue{app_kubernetes_io_name=\"$app\",namespace=\"$namespace\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "# of requests",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests per process",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(phpfpm_process_requests{app_kubernetes_io_name=\"$app\", namespace=\"$namespace\"}) by (pod,child)",
     "legendFormat": "{{pod}} {{child}}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "# of Active & Idle processes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(phpfpm_active_processes{app_kubernetes_io_name=\"$app\", namespace=\"$namespace\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "# of active processes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(phpfpm_idle_processes{app_kubernetes_io_name=\"$app\", namespace=\"$namespace\"})",
     "legendFormat": "# of idle processes"
    },
    {
     "expr": "sum(phpfpm_total_processes{app_kubernetes_io_name=\"$app\", namespace=\"$namespace\"})",
     "legendFormat": "# of total processes"
    }
   ]
  },
  {
   "title": "Total process utilisation & container termination",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg((sum(phpfpm_active_processes{app_kubernetes_io_name=\"$app\",namespace=\"$namespace\"}) by (kubernetes_pod_name) *100) / sum(phpfpm_total_processes{app_kubernetes_io_name=\"$app\",namespace=\"$namespace\"}) by (kubernetes_pod_name))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Process utilisation",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{pod=~\"static-thread-handling-.*\"})",
     "legendFormat": "# of pod terminations"
    }
   ]
  },
  {
   "title": "# of pods in a ReplicaSet",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_replicaset_spec_replicas{replicaset=~\"$app-.*\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{replicaset}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{pod=~\"$app-.*\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "pods"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{pod=~\"$app-.*\", namespace=\"$namespace\"}) by (hostname))",
     "legendFormat": "hosts"
    }
   ]
  }
 ]
}