{
 "title": "Redis Dashboard",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(redis_up, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(redis_up{namespace=\"$namespace\"}, app_kubernetes_io_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{app_kubernetes_io_instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_clients{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"}  / redis_memory_max_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"} )"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"} ",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"}[5m])",
     "legendFormat": "Input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"}[5m])",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"}) - sum (redis_db_keys_expiring{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"} [5m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Redis connected clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_connected_clients{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$instance\"}",
     "legendFormat": "Connected Clients"
    }
   ]
  }
 ]
}