{
 "title": "Resource Calibration v3",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"${ns}\"},podname)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"${ns}\",podname=\"${pod}\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Suggerimenti", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Requests Dev (millicpu)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(quantile_over_time(.95,container_cpu_usage_irate2{container=\"${container}\",namespace=\"${ns}\", podname=\"${pod}\"}[7d]))*1000",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "CPU Requests Prod (millicpu)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(1.5 * quantile_over_time(.99,container_cpu_usage_irate2{container=\"${container}\",namespace=\"${ns}\", podname=\"${pod}\"}[7d]))*1000",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Memory Dev (Mi)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(quantile_over_time(.95,container_memory_working_set_bytes{container=\"${container}\",namespace=\"${ns}\", podname=\"${pod}\"}[7d]))/1048576",
     "legendFormat": "Requests"
    },
    {
     "expr": "1.5*max(quantile_over_time(.95,container_memory_working_set_bytes{container=\"${container}\",namespace=\"${ns}\", podname=\"${pod}\"}[7d]))/1048576",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory Prod (Mi)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1.5 * max(quantile_over_time(.99,container_memory_working_set_bytes{container=\"${container}\",namespace=\"${ns}\", podname=\"${pod}\"}[7d]))/1048576",
     "legendFormat": "Requests"
    },
    {
     "expr": "1.5*1.5 * max(quantile_over_time(.99,container_memory_working_set_bytes{container=\"${container}\",namespace=\"${ns}\", podname=\"${pod}\"}[7d]))/1048576",
     "legendFormat": "Limits"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Requests",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg(1.5 * quantile_over_time(.99,container_cpu_usage_irate2{container=\"${container}\",namespace=\"${ns}\", podname=\"${pod}\"}[7d]))",
     "legendFormat": "Suggested Prod Requests"
    },
    {
     "expr": "avg(quantile_over_time(.95,container_cpu_usage_irate2{container=\"${container}\",namespace=\"${ns}\", podname=\"${pod}\"}[7d]))",
     "legendFormat": "Suggested Dev Requests"
    },
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{container=\"${container}\",namespace=\"${ns}\", podname=\"${pod}\"}[5m]))",
     "legendFormat": "Current Usage"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{container=\"${container}\",namespace=\"${ns}\", podname=\"${pod}\",resource=\"cpu\"})",
     "legendFormat": "Current Request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{container=\"${container}\",namespace=\"${ns}\", podname=\"${pod}\",resource=\"cpu\"})",
     "legendFormat": "Current Limit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(quantile_over_time(.95,container_memory_working_set_bytes{container=\"${container}\",namespace=\"${ns}\", podname=\"${pod}\"}[7d]))",
     "legendFormat": "Suggested Dev Requests"
    },
    {
     "expr": "max(1.5 * max(quantile_over_time(.99,container_memory_working_set_bytes{container=\"${container}\",namespace=\"${ns}\", podname=\"${pod}\"}[7d])))",
     "legendFormat": "Suggested Prod Requests"
    },
    {
     "expr": "max(container_memory_working_set_bytes{container=\"${container}\",namespace=\"${ns}\", podname=\"${pod}\"})",
     "legendFormat": "Current Usage"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{container=\"${container}\",namespace=\"${ns}\", podname=\"${pod}\",resource=\"memory\"})",
     "legendFormat": "Current Requests"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{container=\"${container}\",namespace=\"${ns}\", podname=\"${pod}\",resource=\"memory\"})",
     "legendFormat": "Current Limit"
    }
   ]
  }
 ]
}