{
 "title": "Xalok Renderer 1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ns",
    "query": {
     "query": "label_values(kube_namespace_status_phase,namespace)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(kube_pod_owner{namespace=~\"[[ns]]\",owner_kind=~\"DaemonSet|StatefulSet|ReplicaSet\"},owner_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Renderer: Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "renderer_requests_per_second{namespace=~\"[[ns]]\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    },
    {
     "expr": "sum(renderer_requests_per_second{namespace=~\"[[ns]]\"})",
     "legendFormat": "Sum of requests per second"
    }
   ]
  },
  {
   "title": "Renderer: Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "renderer_requests_error_total{namespace=~\"[[ns]]\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(renderer_up{namespace=~\"[[ns]]\"})",
     "legendFormat": "Renderers"
    }
   ]
  },
  {
   "title": "Renderer: mean time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "renderer_requests_mean_time_in_mills{namespace=~\"[[ns]]\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    },
    {
     "expr": "avg(renderer_requests_mean_time_in_mills{namespace=~\"[[ns]]\"})",
     "legendFormat": "Global Average"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=~\"[[ns]]\", pod =~ \"[[app]].*\",container=\"xalok-renderer\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=~\"[[ns]]\",container=\"xalok-renderer\",pod=~\"[[app]].*\"} / (1024*1024)) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}